using College_Registration.Data;
using Microsoft.OpenApi.Models;
using College_Registration.Domain.Entities;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDbContext<Entities>(options => options.UseSqlServer(builder.Configuration.GetConnectionString("CollegeEnrollemt")));

// Add services to the container.

builder.Services.AddControllersWithViews();

builder.Services.AddSwaggerGen(c=>{
    c.DescribeAllParametersInCamelCase();
    c.AddServer(new OpenApiServer { Description = "Development Server", Url = "https://localhost:7283" });
    c.CustomOperationIds(e => $"{e.ActionDescriptor.RouteValues["action"] + e.ActionDescriptor.RouteValues["controller"]}");
});

builder.Services.AddScoped<Entities>();

var app = builder.Build();

var entities = app.Services.CreateScope().ServiceProvider.GetService<Entities>();
entities.Database.EnsureCreated();


if (!entities.Colleges.Any())
{
    College[] collegeToSeed = new College[]
{
    new ("University of the Philippines Diliman","Diliman Quezon City"),
    new ("Ateneo de Manila University","Katipunan Road, Loyola Heights Quezon City"),
    new ("University of Santo Tomas","España Street, Sampaloc Manila"),
    new ("Polytechnic University of the Philippines","Anonas Street, Sta. Mesa Manila"),
    new ("University of San Carlos","P. del Rosario Street Cebu City"),
    new ("Visayas State University","Visca Baybay"),
    new ("Southern Leyte State University","Brgy. San Roque Sogod"),
    new ("The University of Manila","546 M.V. De Los Santos Street, Sampaloc Manila"),
};
    entities.Colleges.AddRange(collegeToSeed);
    entities.SaveChanges();
}

if (!entities.Courses.Any())
{
    Course[] courseToSeed = new Course[]
{
    new ("Bachelor of Arts in Philosophy","A 4-year course that teaches you the underlying principles of reality, knowledge, morality, and existence and how it applies to other fields."),
    new ("Bachelor of Fine Arts Major in Industrial Design","A 4-year course that teaches how to design and develop usable products and also how to design packaging and systems."),
    new ("Bachelor of Fine Arts Major in Sculpture","A 4-year course that teaches you how to express interests and ideas in three-dimensional (3-D) art."),
    new ("Bachelor of Arts in Psychology","A 4-year course that deals with the study of the way we think and behave."),
    new ("Bachelor of Science in Psychology","A 4-year course that deals with the study of the way we think and behave."),
    new ("Bachelor of Science in Criminology","A 4-year course that is mainly concerned with the nature of crimes and criminals."),
    new ("Bachelor of Arts in Linguistics","A 4-year course that will teach you about languages, their origins, development, and their social significance to man."),
   new ("Bachelor of Science in Forensic Science","A 4-year course that will train you in using scientific principles and techniques to solve different crimes."),
    new ("Bachelor of Arts in Islamic Studies","A 4-year course that is concerned with the study Islam as a way of life in the context of economic, social, cultural, political, and legal aspects."),
    new ("Bachelor of Science in Fisheries","A 4-year course that will train you in aquaculture, capture fisheries, post-harvest fisheries, aquatic ecology, and fisheries-related research."),
    new ("Bachelor of Science in Biology","A 4-year course that deals with the study of living things."),
    new ("Bachelor of Science in Physics","A 4-year course that will teach you about the laws of nature and how to use these laws to understand and explain how the things around us work."),
    new ("Bachelor of Science in Information Technology","A 4-year course that deals with the processing and distribution of data with emphasis on its application on businesses."),
   new ("Bachelor of Science in Statistics","A 4-year course that will teach you about different statistical methods and how to use them to analyze and interpret data."),
 };
    entities.Courses.AddRange(courseToSeed);
    entities.SaveChanges();
}

if (!entities.Subjects.Any())
{
    Subject[] subjectToSeed = new Subject[]
{
      new ("Introduction to Computing",3),
      new ("Computer Programming",3),
      new ("Advance Computer Programming",3),  
      new ("Data Structures and Algorithms ",3),
      new ("Information Management",3),
      new ("Application Development and Emerging Technologies",3),
      new ("Human-computer interaction",3),
      new ("Information Assurance and Security",3),
      new ("Advanced Information Assurance and Security",3),
      new ("Database Management System",3),
      new ("Advanced Database Management System",3),
      new ("Integrative Programming and Technologies",3),
      new ("Computer Networking 1 ",3),
      new ("Computer Networking 2 ",3),
      new ("System Administration and Maintenance",3),
      new ("System Integration and Architecture",3),
      new ("Social Issues and Professional Practice ",3),
      new ("Creative Writing for Beginners",3),
      new ("Elective I",3),
      new ("National Service Training Program 1",3),
      new ("Fitness Exercises for Specific Sports",3),
      new ("Purposive Communication",3),
      new ("Readings in Philippine History",3),
      new ("Spanish 1 – Basic",3),
      new ("Entrepreneurial Mind",3),
      new ("Introduction to Fiction",3),
      new ("Fiction Workshop",3),
      new ("Philippine Literary History",3),
      new ("Mathematics in the Modern World",3),
      new ("Physical Activities Towards Health and Fitness in Dance",3),
      new ("Living the Christian Vision in the Contemporary World",3),
      new ("Art Appreciation",3),
      new ("Introduction to Nonfiction",3),
      new ("Nonfiction Workshop",3),
      new ("Introduction to Drama",3),
      new ("Playwriting Workshop",3),
      new ("Shakespeare",3),
      new ("Creative Writing Research",3),
      new ("Literary Translation",3),
      new ("Latin American Literature",3),
      new ("Anglo-American Literature",3),
      new ("Scriptwriting for Film and Television",3),
      new ("Writing for Children and Young Adult",3),
      new ("Introduction to Children’s and Young Adult Literature",3),
      new ("Contemporary Philippine Literature",3),
      new ("Speculative Fiction",3),
      new ("Current Trends in World Literature",3),
      new ("Practicum",3),
      new ("The Contemporary World",3),
      new ("Introduction to Poetry",3),
      new ("Ethics",3),
      new ("The Great Works",3),
      new ("Life and Works of Rizal",3),
      new ("Human Enhancement",3),
      new ("Science, Technology, and Society",3),
      new ("Christian Vision of the Church in Society",3)

   };
    entities.Subjects.AddRange(subjectToSeed);
    entities.SaveChanges();
}

if (!entities.Accounts.Any())
{
    Account[] accountToSeed = new Account[]
{
    new ("Gerald","Flores",true,"gpf.lpvp@gmail.com","Student","a"),
   };
    entities.Accounts.AddRange(accountToSeed);
    entities.SaveChanges();
}

if (!entities.Sections.Any())
{
    int college=1, course=1;
    Section[] sectionToSeed = new Section[]
    {
        new("Section A",college,course,35),
        new("Section B",college,course, 35),
        new("Section C",college,course, 35),
        new("Section D",college,course, 35),
        new("Section E",college,course, 35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),
        //--------------------------------------------------
        new("Section A",(college+=1),(course-=13),35),
        new("Section B",college,course, 35),
        new("Section C",college,course, 35),
        new("Section D",college,course, 35),
        new("Section E",college,course, 35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),
        //--------------------------------------------------
        new("Section A",(college+=1),(course-=13),35),
        new("Section B",college,course, 35),
        new("Section C",college,course, 35),
        new("Section D",college,course, 35),
        new("Section E",college,course, 35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),
        //--------------------------------------------------
                new("Section A",(college+=1),(course-=13),35),
        new("Section B",college,course, 35),
        new("Section C",college,course, 35),
        new("Section D",college,course, 35),
        new("Section E",college,course, 35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),
        //--------------------------------------------------
                new("Section A",(college+=1),(course-=13),35),
        new("Section B",college,course, 35),
        new("Section C",college,course, 35),
        new("Section D",college,course, 35),
        new("Section E",college,course, 35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),
        //--------------------------------------------------
                new("Section A",(college+=1),(course-=13),35),
        new("Section B",college,course, 35),
        new("Section C",college,course, 35),
        new("Section D",college,course, 35),
        new("Section E",college,course, 35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),
        //--------------------------------------------------
                new("Section A",(college+=1),(course-=13),35),
        new("Section B",college,course, 35),
        new("Section C",college,course, 35),
        new("Section D",college,course, 35),
        new("Section E",college,course, 35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),
        //--------------------------------------------------
                new("Section A",(college+=1),(course-=13),35),
        new("Section B",college,course, 35),
        new("Section C",college,course, 35),
        new("Section D",college,course, 35),
        new("Section E",college,course, 35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),

        new("Section A",college,(course+=1),35),
        new("Section B",college,course,35),
        new("Section C",college,course,35),
        new("Section D",college,course,35),
        new("Section E",college,course,35),
        new("Section F",college,course,35),
        new("Section G",college,course,35),
        new("Section H",college,course,35),
        new("Section I",college,course,35),
        new("Section J",college,course,35),
        //--------------------------------------------------
    };

    entities.Sections.AddRange(sectionToSeed);
    entities.SaveChanges();
}

if (!entities.Schedules.Any())
{
    Schedule[] scheduleToSeed = new Schedule[]
{
    new ("Gerald","Flores",true,"gpf.lpvp@gmail.com","Student","a"),
   };
    entities.Schedules.AddRange(scheduleToSeed);
    entities.SaveChanges();
}


app.UseCors(builder => builder.WithOrigins("*").AllowAnyMethod().AllowAnyHeader());
app.UseSwagger().UseSwaggerUI();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();


app.MapControllerRoute(
    name: "default",
    pattern: "{controller}/{action=Index}/{id?}");

app.MapFallbackToFile("index.html"); ;

app.Run();
